import matplotlib.pyplot as plt
import os
import argparse
from scipy.optimize import curve_fit
import numpy as np
import pandas as pd
from Bio import Phylo

def log_func(x, a, b):
    return a * np.log(x) + b

def log_func_fixed(xs, a, b):
    out = []
    for x in xs:
        out.append(-800 * np.log(x) + 3000)
    return out

def log_func2(xs, b, a):
    out = []
    for x in xs:
        out.append(float(a) * np.log(x) + float(b))
    return out

def exp_func(x, a, b):
    return a * np.exp(x) + b

def parse_flags():
    parser = argparse.ArgumentParser()
    # parse args
    parser.add_argument("-i", "--input",                help="Geneparser output folder location",                     type=str, required=True)
    parser.add_argument("-g", "--genome-progression",   help="Graph data generated by genome progression",            action="store_true", dest="gen")
    parser.add_argument("-p", "--identity-progression", help="Graph data generated by identity/coverage progression", action="store_true", dest="ident")
    parser.add_argument("-m", "--roary-matrix",         help="Graph a roary matrix of shared genes",                  action="store_true", dest="matrix")
    parser.add_argument("-t", "--newick-tree",          help="Newick tree file for the matrix graph",                 type=str, default="", dest="tree")
    parser.add_argument("-l", "--tree-labels",          help="Add labels to tree plot",                               action="store_true", dest="labels")

    return parser.parse_args()

flags = parse_flags()

def plot_geonome_progression():
    # find file
    cutoff = 0
    if os.path.exists("core_pan.csv"):
        core_counts, pan_counts = [], []
        with open("core_pan.csv", "r") as file:
            for n, line in enumerate(file):
                if n >= cutoff:
                    parts = line.rstrip().split(",")
                    pan_counts.append(int(parts[0]))
                    core_counts.append(int(parts[1]))

        core_counts[0], core_counts[1] = pan_counts[0], pan_counts[1]
        count = len(core_counts)
        x = [float(num) for num in list(range(cutoff + 1,count + cutoff + 1))]
        fig, ax1 = plt.subplots()
        # ax2 = ax1.twinx()

        ax1.plot(x, pan_counts, "o", color="b", label="Pan Genome")
        ax1.plot(x, core_counts, "o", color="g", label="Core Genome")

        # curve fit
        pan_fit = np.polyfit(np.log(x), pan_counts, 1)
        core_fit = curve_fit(lambda t,a,b: a+b*np.log(t),  x,  core_counts, p0=(2000., -600.))
        print(core_fit)
        # core_fit = np.polyfit(np.log(x), core_counts, 1)
        # print(core_fit)

        # fit line
        pan2 = log_func(x, *pan_fit)
        # core2 = log_func_fixed(x, *core_fit)
        core2 = log_func2(x, *core_fit[0])
        ax1.plot(x, pan2, color="b")
        ax1.plot(x, core2, color="g")
        ax1.set_ylabel("Number of genes")
        ax1.set_xlabel("Number of genomes")
        plt.xlim(cutoff + 1, count)
        plt.legend(loc="upper left")
        plt.show()
    else:
        exit("Unable to find core_pan.csv in output folder")

def plot_identity_progression():
    # find file
    if os.path.exists("values_list.csv"):
        core_counts, pan_counts, unique_counts, overlap_counts, identities, coverages = [], [], [], [], [], []
        with open("values_list.csv", "r") as file:
            for line in file:
                parts = line.rstrip().split(",")
                identities.append(float(parts[0]))
                coverages.append(float(parts[1]))
                core_counts.append(float(parts[3]))
                pan_counts.append(float(parts[4]))
                unique_counts.append(float(parts[5]))
                overlap_counts.append(float(parts[6]))

        plt.plot(identities, pan_counts, "-o", color="b", label="Pan Genome")
        plt.plot(identities, core_counts, "-o", color="g", label="Core Genome")
        plt.plot(identities, unique_counts, "-o", color="r", label="Unique Genes")
        plt.plot(identities, overlap_counts, "-o", color="m", label="Core/Pan Overlap Genes")
        plt.legend(loc="upper right")
        plt.xlabel("Percent Indentity Cutoff")
        plt.ylabel("Number of Genes")
        plt.show()
    else:
        exit("Unable to find value_list.csv in output folder")

def plot_matrix():
    ### Thanks Marco Galardini
    # read in tree file
    tree = Phylo.read(flags.tree, 'newick')

    tree_order = [t.name for t in tree.get_terminals()]

    # Max distance to create better plots
    mdist = max([tree.distance(tree.root, x) for x in tree.get_terminals()])
    # create dataframe 
    pan_genome_df = pd.read_csv("pan_genome.csv", header=0)

    fig = plt.figure(figsize=(17, 10))
    ax1 = plt.subplot2grid((1,40), (0, 10), colspan=30)
    # transpose and ordering of the df based off the tree order
    a = ax1.matshow(pan_genome_df.T.reindex(tree_order), cmap=plt.cm.Blues,
               vmin=0, vmax=1,
               aspect='auto',
               interpolation='none',
                )
    ax1.set_yticks([])
    ax1.set_xticks([])
    ax1.axis('off')

    ax = fig.add_subplot(1,2,1)
    ax=plt.subplot2grid((1,40), (0, 0), colspan=10, facecolor='white')

    fig.subplots_adjust(wspace=0, hspace=0)

    ax1.set_title('Roary matrix\n(%d gene clusters)'%pan_genome_df.shape[0])

    if flags.labels:
        fsize = 12 - 0.1*pan_genome_df.shape[1]
        if fsize < 7:
            fsize = 7
        with plt.rc_context({'font.size': fsize}):
            Phylo.draw(tree, axes=ax, 
                       show_confidence=False,
                       label_func=lambda x: str(x)[:10],
                       xticks=([],), yticks=([],),
                       ylabel=('',), xlabel=('',),
                       xlim=(-mdist*0.1,mdist+mdist*0.45-mdist*pan_genome_df.shape[1]*0.001),
                       axis=('off',),
                       title=('Tree\n(%d strains)'%pan_genome_df.shape[1],), 
                       do_show=False,
                      )
    else:
        Phylo.draw(tree, axes=ax, 
                       show_confidence=False,
                       label_func=lambda x: None,
                       xticks=([],), yticks=([],),
                       ylabel=('',), xlabel=('',),
                       xlim=(-mdist*0.1,mdist+mdist*0.1),
                       axis=('off',),
                       title=('Tree\n(%d strains)'%pan_genome_df.shape[1],),
                       do_show=False,
                      )

    plt.show()

if __name__ == "__main__":
    os.chdir(flags.input)
    if flags.gen:
        plot_geonome_progression()
    if flags.ident:
        plot_identity_progression()
    if flags.matrix:
        if flags.tree:
            plot_matrix()
        else:
            print("Specify a newick tree file with -t for the matrix output")
